version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    cooldown:
      default-days: 5
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 5
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
